{
 "title": "OLTs_DTC",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Grupo",
    "label": "Grupo",
    "query": {}
   },
   {
    "name": "OLT",
    "label": "OLT",
    "query": {}
   },
   {
    "name": "SLOT",
    "label": "SLOT",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "ONU Status [$OLT] / [$SLOT] ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "ONUs" },
     "functions": [
      {
       "$$hashKey": "object:2020",
       "def": {
        "category": "Transform",
        "defaultParams": [
         0
        ],
        "name": "removeBelowValue",
        "params": [
         { "name": "number", "type": "float" }
        ]
       },
       "params": [ "2" ],
       "text": "removeBelowValue(2)"
      },
      {
       "$$hashKey": "object:2021",
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      },
      {
       "$$hashKey": "object:2022",
       "def": {
        "category": "Transform",
        "defaultParams": [
         100
        ],
        "name": "scale",
        "params": [
         {
          "name": "factor",
          "options": [
           100,
           0.01,
           10,
           -1
          ],
          "type": "float"
         }
        ]
       },
       "params": [ "0.5" ],
       "text": "scale(0.5)"
      },
      {
       "$$hashKey": "object:2023",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "DOWN" ],
       "text": "setAlias(DOWN)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "$OLT" },
     "item": { "filter": "/Status - ONU.*/" },
     "itemTag": { "filter": "ONUs" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "ONUs" },
     "functions": [
      {
       "$$hashKey": "object:2047",
       "def": {
        "category": "Transform",
        "defaultParams": [
         0
        ],
        "name": "removeAboveValue",
        "params": [
         { "name": "number", "type": "float" }
        ]
       },
       "params": [ "1" ],
       "text": "removeAboveValue(1)"
      },
      {
       "$$hashKey": "object:2048",
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      },
      {
       "$$hashKey": "object:2049",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "UP" ],
       "text": "setAlias(UP)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "$OLT" },
     "item": { "filter": "/Status - ONU.*/" },
     "itemTag": { "filter": "Application: ONUs" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ONU Status [$OLT] / [$SLOT] ",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "ONUs" },
     "functions": [
      {
       "$$hashKey": "object:1951",
       "def": {
        "category": "Transform",
        "defaultParams": [
         0
        ],
        "name": "removeBelowValue",
        "params": [
         { "name": "number", "type": "float" }
        ]
       },
       "params": [ "2" ],
       "text": "removeBelowValue(2)"
      },
      {
       "$$hashKey": "object:1952",
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      },
      {
       "$$hashKey": "object:1953",
       "def": {
        "category": "Transform",
        "defaultParams": [
         100
        ],
        "name": "scale",
        "params": [
         {
          "name": "factor",
          "options": [
           100,
           0.01,
           10,
           -1
          ],
          "type": "float"
         }
        ]
       },
       "params": [ "0.5" ],
       "text": "scale(0.5)"
      },
      {
       "$$hashKey": "object:1954",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "$SLOT DOWN" ],
       "text": "setAlias($SLOT DOWN)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "$OLT" },
     "item": { "filter": "/Status - ONU.*/" },
     "itemTag": { "filter": "Application: ONUs" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "ONUs" },
     "functions": [
      {
       "$$hashKey": "object:1978",
       "def": {
        "category": "Transform",
        "defaultParams": [
         0
        ],
        "name": "removeAboveValue",
        "params": [
         { "name": "number", "type": "float" }
        ]
       },
       "params": [ "1" ],
       "text": "removeAboveValue(1)"
      },
      {
       "$$hashKey": "object:1979",
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      },
      {
       "$$hashKey": "object:1980",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "$SLOT UP" ],
       "text": "setAlias($SLOT UP)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "$OLT" },
     "item": { "filter": "/Status - ONU.*/" },
     "itemTag": { "filter": "Application: ONUs" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "$OLT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "repeat": "OLT",
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "ONUs" },
     "functions": [
      {
       "$$hashKey": "object:2211",
       "def": {
        "category": "Transform",
        "defaultParams": [],
        "name": "rate",
        "params": []
       },
       "params": [],
       "text": "rate()"
      },
      {
       "$$hashKey": "object:2212",
       "def": {
        "category": "Transform",
        "defaultParams": [
         100
        ],
        "name": "offset",
        "params": [
         {
          "name": "delta",
          "options": [
           -100,
           100
          ],
          "type": "float"
         }
        ]
       },
       "params": [ "1" ],
       "text": "offset(1)"
      },
      {
       "$$hashKey": "object:2213",
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      },
      {
       "$$hashKey": "object:2214",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "TOTAL ONUs" ],
       "text": "setAlias(TOTAL ONUs)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "$OLT" },
     "item": { "filter": "/Status - ONU.*/" },
     "itemTag": { "filter": "Application: ONUs" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "ONUs" },
     "functions": [
      {
       "$$hashKey": "object:2238",
       "def": {
        "category": "Transform",
        "defaultParams": [
         0
        ],
        "name": "removeAboveValue",
        "params": [
         { "name": "number", "type": "float" }
        ]
       },
       "params": [ "1" ],
       "text": "removeAboveValue(1)"
      },
      {
       "$$hashKey": "object:2239",
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      },
      {
       "$$hashKey": "object:2240",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "TOTAL ONUs UP" ],
       "text": "setAlias(TOTAL ONUs UP)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "$OLT" },
     "item": { "filter": "/Status - ONU.*/" },
     "itemTag": { "filter": "Application: ONUs" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "ONUs" },
     "functions": [
      {
       "$$hashKey": "object:2263",
       "def": {
        "category": "Transform",
        "defaultParams": [
         0
        ],
        "name": "removeBelowValue",
        "params": [
         { "name": "number", "type": "float" }
        ]
       },
       "params": [ "2" ],
       "text": "removeBelowValue(2)"
      },
      {
       "$$hashKey": "object:2264",
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      },
      {
       "$$hashKey": "object:2265",
       "def": {
        "category": "Transform",
        "defaultParams": [
         100
        ],
        "name": "scale",
        "params": [
         {
          "name": "factor",
          "options": [
           100,
           0.01,
           10,
           -1
          ],
          "type": "float"
         }
        ]
       },
       "params": [ "0.5" ],
       "text": "scale(0.5)"
      },
      {
       "$$hashKey": "object:2266",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "TOTAL ONUs DOWN" ],
       "text": "setAlias(TOTAL ONUs DOWN)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "$OLT" },
     "item": { "filter": "/Status - ONU.*/" },
     "itemTag": { "filter": "Application: ONUs" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU OLT $OLT",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:2323",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "CPU OLT" ],
       "text": "setAlias(CPU OLT)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "$OLT" },
     "item": { "filter": "Active CPU load last 1 minute" },
     "itemTag": { "filter": "Application: System Monitor" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "MEMÓRIA OLT $OLT",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "System Monitor" },
     "functions": [
      {
       "$$hashKey": "object:2904",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Memória OLT" ],
       "text": "setAlias(Memória OLT)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "$OLT" },
     "item": { "filter": "Available memory last 1 minute" },
     "itemTag": { "filter": "Application: System Monitor" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Trafego RX das portas GPON",
   "type": "bargauge",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "Network interfaces" },
     "group": { "filter": "OLT" },
     "host": { "filter": "$OLT" },
     "item": {
      "filter": "/Interface gpon.*: Bits received/"
     },
     "itemTag": {
      "filter": "Application: Network interfaces"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Trafego TX das portas GPON",
   "type": "bargauge",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "Network interfaces" },
     "group": { "filter": "OLT" },
     "host": { "filter": "$OLT" },
     "item": { "filter": "/Interface gpon.*: Bits sent/" },
     "itemTag": { "filter": "interface" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Trafego RX das portas Gigabit",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "Network interfaces" },
     "group": { "filter": "OLT" },
     "host": { "filter": "$OLT" },
     "item": {
      "filter": "/Interface gigabit.*: Bits received/"
     },
     "itemTag": {
      "filter": "Application: Network interfaces"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Trafego TX das portas Gigabit",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "Network interfaces" },
     "group": { "filter": "OLT" },
     "host": { "filter": "$OLT" },
     "item": {
      "filter": "/Interface gigabit.*: Bits sent/"
     },
     "itemTag": {
      "filter": "Application: Network interfaces"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Trafego RX das portas Ten-Gigabit",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "Network interfaces" },
     "group": { "filter": "OLT" },
     "host": { "filter": "$OLT" },
     "item": {
      "filter": "/Interface ten-gigabit.*: Bits received/"
     },
     "itemTag": {
      "filter": "Application: Network interfaces"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Trafego TX das portas Ten-Gigabit",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "Network interfaces" },
     "group": { "filter": "OLT" },
     "host": { "filter": "$OLT" },
     "item": {
      "filter": "/Interface ten-gigabit.*: Bits sent/"
     },
     "itemTag": {
      "filter": "Application: Network interfaces"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Trafego RX das portas LAG",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "Network interfaces" },
     "group": { "filter": "OLT" },
     "host": { "filter": "$OLT" },
     "item": {
      "filter": "/Interface lag.*: Bits received/"
     },
     "itemTag": {
      "filter": "Application: Network interfaces"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Trafego TX das portas LAG",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "Network interfaces" },
     "group": { "filter": "OLT" },
     "host": { "filter": "$OLT" },
     "item": { "filter": "/Interface lag.*: Bits sent/" },
     "itemTag": { "filter": "interface" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}